### ISSUE TITLE
iteration depend previous annealing

### ISSUE THREAD

**Issue by yuyamashiro** [OpenJij/OpenJij#12]
iteration で複数回 annealing したときにスピンの状態を初期化していないので、前のアニーリングの結果に引きずられているっぽい。ちゃんと初期化しないといけない。
c++側で初期化メソッドを作るか、python側でiterationのたびにcxxjij.graph.Graphインスタンスを再生性しないいけない。

**Comment by j-i-k-o** [comment]
これに関してはその通りで、Modelクラスがスピン状態を保存しているので連続でアニーリング回すには初期化メソッド作る必要があります。
C++側でinit_spin的な関数を実装する予定です。

**Comment by yuyamashiro** [comment]
close by #19
