### ISSUE TITLE
Use Tox

### ISSUE THREAD

**Issue by 29rou** [OpenJij/OpenJij#200]
``` Bash
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
```

**Comment by j-i-k-o** [comment]
We have discussed the topic in https://github.com/OpenJij/OpenJij/issues/125 but we currently have no idea how to run C++ test with pytest.

**Comment by 29rou** [comment]
ここら辺のコードが気になりますね。
https://github.com/pybind/cmake_example/blob/ce0ea77878522a85da0be13cf9e425626d05827e/setup.py#L126

**Comment by 29rou** [comment]
https://github.com/pytest-dev/pytest-cpp

**Comment by durga0201** [comment]
`import os
import subprocess

def run_tests():
    # Build the C++ test executable
    subprocess.run(['g++', 'test_example.cpp', '-o', 'test_example', '-lgtest', '-lpthread'])

    # Run the tests using pytest-cpp
    subprocess.run(['pytest', '--cpp', 'test_example'])

    # Clean up
    os.remove('test_example')

if __name__ == '__main__':
    run_tests()`

**Comment by durga0201** [comment]
the above caode can be used for c++ test cases

**Comment by 29rou** [comment]
> We can use Cmake and build test cases and run that using pytest.

Thank you very much! The CI for GitHub Actions has become really easy to use, so I've decided not to introduce Tox. However, I really appreciate the comments on the ISSUE. Thank you very much!
