### ISSUE TITLE
support dimod 0.10.13

### ISSUE THREAD

**Issue by yuyamashiro** [OpenJij/OpenJij#237]
**Describe the bug**

see dimod release note https://github.com/dwavesystems/dimod/releases/tag/0.10.13
> Deprecate support for a 2-tuple of (dict, list) as a samples-like. E.g. ({'a': 1, 'b': 0}, ['a', 'b']) is no longer supported. (array_like, labels) is still supported, as is a dictionary. Support will be removed in dimod 0.12.0.

**To Reproduce**

```python
import openjij as oj

sampler = oj.SASampler()
res = sampler.sample_qubo({("a","b"):1, ("d","a"):2})
```

> ValueError: samples_like and labels dimensions do not match

**How to fix**

change

https://github.com/OpenJij/OpenJij/blob/28c1dcf341d9d6cf2758d162fed488adb20d5435/openjij/sampler/sampler.py#L133-L136

 to

```python
        response = openjij.Response.from_samples(
            states, model.vartype, energies,
            info=system_info
        )
```

because `states` is a dictionary.

**Comment by K-Suzuki-Jij** [comment]
Fixed in [v0.4.7.](https://github.com/OpenJij/OpenJij/releases/tag/v0.4.7)
