### ISSUE TITLE
cmake fails when installing OpenJij with CUDA/GPU

### ISSUE THREAD

**Issue by italogs** [OpenJij/OpenJij#360]
**Describe the bug**
I am unable to conclude the installation of OpenJij with CUDA/GPU.
The error log seems quite complicated for me to understand. It seems that cmake cannot compile openjij and jij-cimod (maybe due to external dependencies).
Conversely, installing OpenJij without CUDA/GPU works fine.

**To Reproduce**
Steps to reproduce the behavior, as in the README.md:

1. pip install -U cmake
1. pip install --no-binary=openjij,jij-cimod openjij

**Expected behavior**
Installation to conclude without errors.

**Screenshots**
There are two screenshots attached for better clarity.
![git-1](https://user-images.githubusercontent.com/2755170/225313817-9ddf6794-b1ee-4b13-9770-4eb0362e8a89.jpg)
![git-2](https://user-images.githubusercontent.com/2755170/225313823-93c082ee-87df-45e1-bca4-581b068ee205.JPG)

**Environment (please complete the following information):**

OS: Ubuntu
Version: Python 3.7
CUDA: 11.7
cmake: 3.22.6
gcc: 9.4.0
OpenJij: 0.6.15 (latest)

**Additional context**
If anyone has it correctly installed, please, show your current environment so I can go towards a promising avenue :)

Thanks.

**Comment by 29rou** [comment]
Thank you for reporting the build error, we will take care of it.
I would like to ask you to try if possible, is it possible to Git Clone and build the package?
Sincerely.

**Comment by 29rou** [comment]
A corrected version of MANIFEST.in has been released.
We believe that in the previous version, the required source code was not included in the package and an error occurred.

**Comment by j-i-k-o** [comment]
Please note that in the current version of OpenJij. It is recommended to use OpenJij with CPU mode since the performance is not so changed compared to GPU.

**Comment by dvnoble** [comment]
Thank you for your prompt response, j-i-k-o. Regarding Issue #360, I've found that the version I tested already includes the fix in the MANIFEST of commit a9753d9. However, I'm still experiencing issues with the Cuda files, specifically an error message stating that "error: 'info' is not a constant expression." If it would be helpful, I can provide the full log for your review. Thank you again, and best regards.

**Comment by italogs** [comment]
Thanks, @29rou and @j-i-k-o, for the quick answers.
The purpose of installing all OpenJij is to test if GPU-based code can surpass CPU-based one. However, as indicated by @j-i-k-o, GPU-based one has not much advantage yet.

After this new round of updates, I am still having problems with cmake. 
If any of you has a working version of GPU-based, could you export all needed environment information and libraries (e.g., cmake version, CUDA version, SO, GCC version, and so on)?
This could help us (as users) a lot in investigating how to properly compile the code on our side.
Thanks in advance!

**Comment by hardy-science** [comment]
![Screenshot (48)](https://user-images.githubusercontent.com/132411027/235807609-1f8561a6-ef1a-4c5f-a919-fa809d1d8a54.png)
I too failed in my attempt to install Openjij with CUDA support. An error is reported when compiling kernel.cu (error: ‘info’ is not a constant expression). I would like to try to Git clone and build the package, but my question is, would that install Openjij with CUDA support?
Many Thanks for your answer in advance.

**Comment by czachow** [comment]
Dear Jiko,

thanks a lot for your reply. I will test the new version of openjij.

Best,
Christopher


Von: jiko ***@***.***>
Antworten an: OpenJij/OpenJij ***@***.***>
Datum: Mittwoch, 9. August 2023 um 15:45
An: OpenJij/OpenJij ***@***.***>
Cc: "Zachow, Christopher" ***@***.***>, Comment ***@***.***>
Betreff: Re: [OpenJij/OpenJij] cmake fails when installing OpenJij with CUDA/GPU (Issue #360)


Thanks for the comments.
We recently removed cuda support from OpenJij due to the following reasons:

  *   Current Cuda support is only for specific types of graphs, which is not suitable for practical applications.
  *   Current CPU implementation usually outperforms the GPU implementation.
#387<https://github.com/OpenJij/OpenJij/pull/387>

Please try the installation process using the latest main branch.
Many thanks.
