### ISSUE TITLE
Failure at building CUDA objects

### ISSUE THREAD

**Issue by dvnoble** [OpenJij/OpenJij#362]
**Describe the bug**
OpenJij can't build from source when using Cuda support.

**To Reproduce**
1 - pip3 install --no-binary=openjij,jij-cimod openjij

**Screenshots**
![image](https://user-images.githubusercontent.com/731763/225931051-a214e578-cfff-4357-b8ac-180b386c9600.png)

**Environment:**

- OS: Ubuntu 22.04.2 Kernel 5.15
- Openjij: 0.6.16 a9753d90
- Cuda compiler: 12.1.66
- CXX: 11.3.0

**Additional context**
The script correctly finds the CUDA toolkit files.

**Comment by j-i-k-o** [comment]
Thanks for the issue.
Please also see this issue  https://github.com/OpenJij/OpenJij/issues/360 which seems to deal with the same topic.
Many thanks.
