### ISSUE TITLE
eigen no more on bitbucket

### ISSUE THREAD

**Issue by gmondo** [OpenJij/OpenJij#96]
the build from scratch does not work anymore

**Comment by gmondo** [comment]
This could solve:
```
root@qc-model:/tmp/OpenJij# git diff
diff --git a/external/eigen.cmake b/external/eigen.cmake
index c2e4694..40171b4 100644
--- a/external/eigen.cmake
+++ b/external/eigen.cmake
@@ -3,7 +3,8 @@ include(FetchContent)
 #### Eigen ####
 FetchContent_Declare(
     eigen
-    URL http://bitbucket.org/eigen/eigen/get/3.3.7.tar.gz
+    GIT_REPOSITORY  https://gitlab.com/libeigen/eigen
+    GIT_TAG         3.3.7
     )

 FetchContent_GetProperties(eigen)
```

**Comment by j-i-k-o** [comment]
Could you please tell me the version of CMake you are using?
We've already confirmed that the build will fail with CMake < 3.12.2.
If you are using older version of CMake, please update to the latest version.

**Comment by Shitaro** [comment]
Anyway, as @gmondo  has pointed out, Eigen should be fetched from GitLab.
See, [News:Migration to GitLab.com scheduled on the December 4th](http://eigen.tuxfamily.org/index.php?title=News:Migration_to_GitLab.com_scheduled_on_the_December_4th)
> https://bitbucket.org/eigen/eigen will be unavailable and replaced by an empty project pointing to https://gitlab.com/libeigen/eigen

**Comment by j-i-k-o** [comment]
I've just submited a pull request #117 following the advice.
@Shitaro Could you please confirm the pull request?

**Comment by j-i-k-o** [comment]
This issue will be closed. Thanks @gmondo  and @Shitaro!
